//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

namespace uniforms {

export interface Form {
    formID?: string | undefined;
    formTitle?: string | undefined;
    description?: string | undefined;
    ownerID?: string | undefined;
    template?: string | undefined;
    questions?: Question[] | undefined;
    responses?: Response[] | undefined;
    tags?: Tag[] | undefined;
}

export interface Question {
    questionID?: string | undefined;
    formID?: string | undefined;
    questionText?: string | undefined;
    questionType?: string | undefined;
    options?: string[] | undefined;
    isRequired?: boolean;
    file?: string | undefined;
}

export interface Response {
    responseID?: string | undefined;
    formID?: string | undefined;
    userID?: string | undefined;
    answers?: string[] | undefined;
}

export interface Tag {
    tagID?: string | undefined;
    name?: string | undefined;
}

export interface Template {
    templateID?: string | undefined;
    templateName?: string | undefined;
    defaultQuestions?: Question[] | undefined;
}

export interface User {
    userID?: string | undefined;
    name?: string | undefined;
    email?: string | undefined;
    role?: string | undefined;
    formsCreated?: Form[] | undefined;
}

export interface FileResponse {
    data: Blob;
    status: number;
    fileName?: string;
    headers?: { [name: string]: any };
}

}